# Generated by Django 2.2.4 on 2019-10-16 21:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrochetHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crochethook_size', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=10)),
                ('count', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_color', models.CharField(max_length=100)),
                ('yarn_texture', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('crochethook_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarns', to='crm.CrochetHook')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='crm.Yarn')),
                ('recipient_name', models.CharField(max_length=100)),
                ('p_description', models.TextField()),
                ('gift_size', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('crochethook_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='crm.CrochetHook')),
            ],
        ),
    ]
