# Generated by Django 2.2.4 on 2020-03-09 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='yarn_amount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crochethook',
            name='count',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='crochethook',
            name='crochethook_size',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gift',
            name='yarn_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Yarn'),
        ),
    ]
